name: llmlearner
channels:
  - conda-forge
  - defaults

dependencies:
  - python=3.10
  - pip
  - numpy
  - pandas
  - scikit-learn
  - matplotlib
  - seaborn
  - tqdm
  - jupyterlab
  - ipywidgets
  - pytorch
  - torchvision
  - torchaudio
  - cudatoolkit=11.8  # only if your RunPod GPU supports CUDA (comment out if CPU only)
  - sentencepiece
  - pip:
      - transformers
      - datasets
      - accelerate
      - bitsandbytes
      - evaluate
      - sacrebleu
      - bert-score
      - umap-learn
      - sae-lens
      - huggingface_hub
      - wandb
      - scipy
      - torchinfo
      - rich
      - pyarrow